dtb-$(CONFIG_ARCH_FSL_LS2085A) += fsl-ls2085a-simu.dtb fsl-ls2085a-qds.dtb fsl-ls2085a-rdb.dtb
dtb-$(CONFIG_ARCH_FSL_LS1043A) += fsl-ls1043a-simu.dtb fsl-ls1043a-emu.dtb fsl-ls1043a-qds.dtb fsl-ls1043a-rdb.dtb fsl-ls1043a-uefi-rdb.dtb

dtb-$(CONFIG_ARCH_FSL_LS1043A) += fsl-ls1043a-qds-minimal.dtb fsl-ls1043a-rdb-minimal.dtb
 
always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
